name: Deploy to VDS

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VDS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }} &&
            git fetch --all &&
            git reset --hard HEAD
            git checkout tags/${{ github.ref_name }}
            echo 'Deployed tag ${{ github.ref_name }} to production'
          
            docker exec php82 sh -c 'cd lingvakit && composer install --no-interaction --prefer-dist' &&
            docker exec php82 sh -c 'cd lingvakit && php artisan migrate' &&
            docker exec php82 sh -c 'cd lingvakit && php artisan cache:clear' &&
            echo 'Deployment and post-steps completed for production.'
          "
